/**
 * User-facing copy. Keep labels here (not inline) so they can move to an i18n
 * catalogue without touching components.
 */
export const strings = {
  auth: {
    title: "Intelligent\nInfrastructure\nPlatform",
    subtitle: "Map, inspect and report public infrastructure from the field.",
    logoLabel: "Intelligent Infrastructure Platform logo",
    continueWithSso: "Continue with SSO",
    continueWithGoogle: "Continue with Google",
    orWithUsername: "or with username",
    usernameLabel: "Username or email",
    usernamePlaceholder: "name@organisation.org",
    passwordLabel: "Password",
    forgotPassword: "Forgot password?",
    showPassword: "Show password",
    hidePassword: "Hide password",
    keepSignedIn: "Keep me signed in on this device",
    signIn: "Sign in",
    newToPlatform: "New to the platform?",
    createAccount: "Create an account",
    changeServer: "Change server",
    serverOnline: "Server reachable",
    serverOffline: "No connection",
    comingSoonTitle: "Coming soon",
    comingSoonMessage: "This option isn't available yet.",
    errors: {
      invalidCredentials: "That username or password is incorrect.",
      ssoOffline: "SSO needs a connection. Sign in with your username instead.",
      ssoFailed: "SSO sign-in didn't complete. Please try again.",
      serverUnreachable: "Could not reach the server. Please try again.",
      accountPending:
        "Your account is waiting for approval. You can sign in once an administrator approves it.",
    },
  },
  register: {
    back: "Back to sign in",
    title: "Create an account",
    subtitle:
      "Join the Intelligent Infrastructure Platform to capture and report assets in your area.",
    nameLabel: "Full name",
    emailLabel: "Work email",
    emailPlaceholder: "name@organisation.org",
    phoneLabel: "Phone number",
    phonePlaceholder: "+256",
    optional: "(optional)",
    passwordLabel: "Password",
    confirmPasswordLabel: "Confirm password",
    passwordHint: "At least 10 characters with a number",
    passwordRule: "at least 10 characters with a number",
    strength: {
      weak: "Weak",
      fair: "Fair",
      strong: "Strong",
      veryStrong: "Very strong",
    },
    termsPrefix: "I agree to the ",
    termsOfUse: "terms of use",
    termsJoin: " and ",
    privacyPolicy: "privacy policy",
    termsSuffix: ", including how photos and locations are stored.",
    verificationNote:
      "We’ll email a verification link. An administrator then approves your role and assigns your project area.",
    submit: "Create account",
    haveAccount: "Already have an account?",
    signIn: "Sign in",
    successTitle: "Check your email",
    successSentTo: "We sent a verification link to",
    successNext:
      "Open it to confirm your address. An administrator then approves your role and assigns your project area.",
    errors: {
      nameRequired: "Enter your full name.",
      emailRequired: "Enter your work email.",
      emailInvalid: "Enter a valid email, like name@organisation.org.",
      phoneInvalid: "Include the country code, like +256 700 123 456.",
      passwordRequired: "Choose a password.",
      passwordWeak: "Use at least 10 characters with a number.",
      confirmMismatch: "The passwords don’t match.",
      termsRequired: "Accept the terms of use and privacy policy to continue.",
    },
    submitErrors: {
      offline:
        "Creating an account needs a connection. Try again when you’re online.",
      email_taken:
        "An account with this email already exists. Sign in instead.",
      invalid: "Some details weren’t accepted. Check the form and try again.",
      server_unreachable: "Could not reach the server. Please try again.",
    },
  },
  categories: {
    energy: {
      label: "Energy & Power",
      description: "Poles, substations, solar, street lights",
    },
    water: {
      label: "Water & Sanitation",
      description: "Boreholes, taps, wells, tanks, toilets",
    },
    telecom: {
      label: "Telecom",
      description: "Masts, telecom poles, cabinets",
    },
    roads: {
      label: "Roads & Drainage",
      description: "Culverts, bridges, potholes, drains",
    },
  },
  tabs: {
    capture: "Capture",
    map: "Map",
    records: "Records",
    review: "Review",
    profile: "Profile",
  },
  syncStatus: {
    pending: "waiting to sync",
    uploading: "uploading",
    synced: "synced",
    failed: "sync failed",
  },
  home: {
    overline: "IIP · {org}",
    overlineNoOrg: "IIP",
    title: "Field capture",
    pending: "{count} pending",
    pendingLabel: "{count} records waiting to sync. Open records",
    profileLabel: "Profile and settings",
    todayLabel: "Today",
    capturedToday: "Captured today",
    synced: "Synced",
    flagged: "Flagged",
    gnss: "GNSS",
    gnssNoFix: "No fix",
    heading: "What are you capturing?",
    aiPick: "Not sure? Let AI pick the category",
    lastCaptured: "Last captured",
    nothingYet: "Nothing captured yet. Pick a category to start.",
  },
  capture: {
    close: "Close camera",
    flashOn: "Flash on",
    flashOff: "Flash off",
    autoCategory: "AI picks category",
    gpsRegion: "GPS accuracy",
    accuracyUnit: "m",
    status: {
      acquiring: "Acquiring accurate fix…",
      imprecise: "Acquiring accurate fix…",
      confirming: "Confirming fix…",
      ready: "Location locked",
      unknown: "GPS precision unknown",
      denied: "Location permission needed",
      error: "Location unavailable",
    },
    satellites: "{count} sats",
    stableFixes: "{count} of 3 stable fixes",
    meterStart: "8 m",
    meterTarget: "Target 4 m",
    meterEnd: "0 m",
    hint: {
      waiting: "Step into open sky, away from walls and trees",
      energy: "Fit the whole pole, top to base",
      water: "Fit the whole structure in the frame",
      telecom: "Fit the whole mast or cabinet in the frame",
      roads: "Frame the full width of the culvert, drain or damage",
      auto: "Fit the whole asset in the frame",
    },
    shutter: "Take photo",
    shutterLocked: "Take photo — locked until GPS accuracy is under 4 metres",
    shutterLockedAr: "Take photo — locked until AR has mapped the ground",
    shutterNoteReady: "Location is stamped when you tap",
    shutterNoteLocked: "Capture unlocks below 4 m",
    saveDraft: "Can’t get below 4 m? Save as draft for review",
    photosTaken: "Photos taken: {count} of 3",
    photoSlot: "Photo {index}. Tap to retake",
    photoOf: "Photo {index} of 3",
    sharp: "sharp",
    blurry: "blurry",
    exposureOk: "exposure OK",
    exposureBad: "check exposure",
    continue: "Continue",
    detected: "{count} detected",
    boxLabel: "{label} · {confidence}",
    boxLabelTimed: "{label} · {confidence} · {ms} ms",
    strip: {
      accuracy: "± {accuracy} m",
      accuracyUnknown: "± — m",
      ar: {
        normal: "AR tracked",
        limited: "AR mapping…",
        unavailable: "AR starting…",
        off: "No AR",
      },
      range: "{distance} m",
      model: "{model} {ms} ms",
    },
    sheet: {
      assetPosition: "Asset position · ±{accuracy} m",
      yourPosition: "Your position · ±{accuracy} m",
      waitingForFix: "Waiting for GPS",
      coordinates: "{latitude} {ns}, {longitude} {ew}",
      offline: "Offline",
      online: "Online",
      photos: "Photos {count}/3",
      placeByTap: "Place by tap",
      cancelPlacing: "Cancel",
      placeHint: "Tap where the asset meets the ground",
      placeFailed: "No ground found there. Tap the asset’s base on the ground.",
      tapLayer: "Camera view. Tap the base of the asset to place it",
      assetAt:
        "{label} at {distance} m — the record takes its position, not yours",
      assetAtSensor:
        "{label} at about {distance} m (from tilt and compass) — the record takes its position",
      mapGround: "Move the phone slowly over the ground to start AR ranging",
      noTarget: "No asset locked. Use Place by tap and tap its base",
    },
    detectionsNone: "Nothing detected yet",
    model: {
      loading: "Loading AI model… {percent}%",
      unavailable:
        "AI detection unavailable. You can still capture; the record is checked after sync.",
    },
    permissions: {
      title: "Camera & location access",
      message:
        "Capture needs the camera, and your location to pin the asset to under 4 m.",
      grant: "Allow access",
    },
    noCamera: "No back camera was found on this device.",
    tag: {
      title: "Tag this asset",
      back: "Back to review",
      step: "Step 3 of 3",
      kept: "{count} detections kept",
      keptOne: "1 detection kept",
      keptNone: "No detections kept",
      category: "Category",
      status: "Status",
      statusHint: "Select all that apply. AI suggestions are pre-selected.",
      pickCategoryFirst: "Pick a category to see its statuses.",
      functional: "Functional?",
      functionalHint: "The AI can’t judge this from a photo.",
      functionalOptions: { yes: "Yes", no: "No", unknown: "Unknown" },
      comment: "Comment",
      commentPlaceholder: "Add notes about the asset…",
      dictate: "Dictate comment",
      stopDictation: "Stop dictation",
      listening: "Listening…",
      dictationFailed: "Voice input didn’t work. Please type the comment.",
      duplicateTitle: "Possible duplicate.",
      duplicateMessage:
        "A {label} ({id}) was recorded {distance} m away on {date}.",
      duplicateAsset: "asset",
      updateExisting: "Update the existing asset",
      newAsset: "This is a new asset",
      latitude: "Latitude",
      longitude: "Longitude",
      elevation: "Elevation (ellipsoid)",
      accuracy: "Accuracy",
      elevationValue: "{value} m",
      accuracyValue: "±{accuracy} m",
      satellites: "{count} sats",
      notReported: "—",
      draftLocation: "Location not verified: saved for supervisor review.",
      saveDraft: "Save draft",
      save: "Save record",
      needCategory: "Pick a category to save.",
      needStatus: "Pick at least one status to save the record.",
      needDuplicate: "Say whether this is the existing asset or a new one.",
      editTitle: "Edit record",
      editBack: "Back to record",
      saveChanges: "Save changes",
    },
    statuses: {
      good: "Good condition",
      inclined: "Inclined",
      vegetation: "Covered by vegetation",
      cracked: "Cracked / damaged",
      rust: "Rust / rot",
      sagging_lines: "Sagging lines",
      under_construction: "Under construction",
      leaking: "Leaking",
      blocked: "Blocked",
      eroded: "Eroded",
      potholes: "Potholes",
      vandalised: "Vandalised",
    },
    errors: {
      captureTitle: "Capture failed",
      captureMessage: "The photo could not be taken.",
      saveTitle: "Save failed",
      saveMessage: "The capture could not be saved. Please try again.",
    },
    review: {
      title: "Review detections",
      back: "Back to camera",
      step: "Step 2 of 3",
      subtitle: "{category} · {count} found · {model} on device",
      autoCategory: "AI category",
      photoSummary: "Photo with {count} detections",
      boxLabel: "{index} {label} · {confidence}",
      legendAccepted: "Pre-accepted ≥ 0.70",
      legendSuggested: "Suggested 0.40–0.70",
      legendGround: "AR ground point",
      away: "{distance} m away",
      aboutAway: "about {distance} m away",
      suggestedShort: "Suggested · {confidence}",
      distantTitle: "{label} (distant)",
      beyondRange:
        "Beyond reliable AR range ({range} m). Accept it as a rough point, or walk closer and capture it on its own.",
      placedByTap: "Placed by tap",
      onDeviceTitle: "Each asset has its own coordinates.",
      onDevice:
        "Detection, ranging and projection all ran on this phone in {ms} ms. Nothing was uploaded.",
      onDeviceUntimed:
        "Detection, ranging and projection all ran on this phone. Nothing was uploaded.",
      computedPosition: "Computed position",
      positionSource: {
        ar_auto: "AR ray × ground plane",
        ar_tap: "Tap × ground plane",
        ground_estimate: "Estimated ground",
        sensor: "Tilt + compass estimate",
        device: "Phone position",
      },
      latitude: "Latitude",
      longitude: "Longitude",
      distanceBearing: "Distance · bearing",
      distanceBearingValue: "{distance} m · {bearing}°",
      positionAccuracy: "Position accuracy",
      accuracyValue: "±{accuracy} m",
      positionNote:
        "Device fix ±{device} m plus projection ±{projection} m. The device stood at {coordinates}.",
      deviceCoordinates: "{latitude}°{ns}, {longitude}°{ew}",
      replace: "Re-place by tapping the base",
      replaceTitle: "Tap the base of {label}",
      replaceHint: "Tap where it meets the ground.",
      replaceFailed:
        "That point isn’t on the ground the phone measured. Tap lower, at the base.",
      replaceCancel: "Cancel",
      replacePhoto: "Photo of {label}. Tap its base",
      attributes: "Attributes",
      diagramYou: "you",
      diagramSummary: "{label} {distance} m from you, bearing {bearing}°",
      confidence: "Confidence {confidence}",
      suggested: "Suggested · confidence {confidence}",
      rejected: "Not an asset · confidence {confidence}",
      accepted: "Accepted",
      accept: "Accept",
      reject: "Not an asset",
      undo: "Undo",
      expand: "Show {label} attributes",
      collapse: "Hide {label} attributes",
      pleaseCheck: "Please check",
      source: {
        high: "AI · high",
        medium: "AI · medium",
        low: "AI · low",
        ai: "AI",
        ar: "AR · from range",
        sensor: "Sensors · estimate",
        gis: "GIS",
        user: "User",
      },
      pending: "Estimated after sync",
      gisPending: "Calculated after sync",
      notMeasured: "Not measured: no AR range",
      edit: "Change {attribute}",
      editTitle: "{attribute}",
      noneFound:
        "No assets were detected. Continue to tag the photo, or add another.",
      addPhoto: "Add photo",
      continue: "Continue to tagging",
    },
  },
  attributes: {
    material: {
      label: "Material",
      values: { concrete: "Concrete", metal: "Metallic", wood: "Wood" },
    },
    inclination: { label: "Inclination", format: "{value}° from vertical" },
    estimatedAge: {
      label: "Estimated age",
      values: {
        "0-5": "0–5 years",
        "5-10": "5–10 years",
        "10-20": "10–20 years",
        "20+": "Over 20 years",
      },
    },
    estimatedHeight: { label: "Estimated height", format: "{value} m" },
    estimatedSize: {
      label: "Estimated size",
      values: { small: "Small", medium: "Medium", large: "Large" },
    },
    vegetationCover: {
      label: "Vegetation cover",
      values: { none: "None", partial: "Partial", heavy: "Heavy" },
    },
    countInFrame: { label: "Count in frame", format: "{value}" },
    distanceFromRoad: { label: "Distance from main road", format: "{value} m" },
  },
  camera: {
    unavailableTitle: "Camera capture",
    unavailableMessage:
      "Camera and AI detection run in the mobile app. Open it on your Android or iOS device to capture assets.",
  },
  records: {
    title: "Records",
    openSearch: "Search records",
    closeSearch: "Close search",
    searchLabel: "Search by name, ID or category",
    searchPlaceholder: "Search by name, ID or category",
    clearSearch: "Clear search",
    filterLabel: "Filter records",
    filters: {
      all: "All · {count}",
      pending: "Pending · {count}",
      flagged: "Flagged · {count}",
    },
    today: "Today",
    yesterday: "Yesterday",
    detections: "{count} detections",
    functional: { yes: "functional", no: "not working" },
    rowLabel: "{title}, {meta}, {status}",
    banner: {
      label: "Sync status",
      waitingOne: "1 record waiting to upload",
      waiting: "{count} records waiting to upload",
      uploading: "Uploading…",
      failed: "{count} failed to upload · tap Sync now to retry",
      offline: "No network · photos upload on Wi-Fi",
      online: "Photos upload on Wi-Fi",
      syncNow: "Sync now",
    },
    scopes: {
      label: "Show records",
      mine: "Mine",
      team: "Team",
    },
    empty: {
      team: "No team records here yet. Pull down to fetch them when online.",
      all: "No records yet. Captures you save appear here.",
      pending: "Nothing waiting to upload.",
      flagged: "No flagged records.",
      search: "No records match your search.",
    },
    detail: {
      capturedBy: "Captured by {name}",
      back: "Back to records",
      photos: "Photos",
      photoCount: "{index} of {count} photos",
      photoOne: "1 photo",
      photoLabel: "Photo {index} of {count}",
      noPhoto: "No photo on this device",
      captured: "{id} · captured {when}",
      capturedNoId: "Captured {when}",
      attributes: "Attributes",
      source: "Source",
      status: "Status",
      noStatus: "Not recorded",
      comment: "Comment",
      location: "Location",
      history: "Condition history",
      thisCapture: "{date} · this capture",
      showOnMap: "Show on map",
      edit: "Edit record",
      notFound: "This record isn’t on this device.",
      backToRecords: "Back to records",
      sync: {
        pending: "Waiting to sync",
        uploading: "Uploading",
        synced: "Synced",
        failed: "Sync failed",
      },
      flagged: "Flagged for review",
      condition: {
        inclined: "inclined {value}°",
        vegetation: {
          none: "no vegetation",
          partial: "partial vegetation",
          heavy: "heavy vegetation",
        },
        none: "No condition recorded",
      },
    },
  },
  recordStatus: {
    synced: "Synced",
    pending: "Pending",
    uploading: "Uploading",
    failed: "Sync failed",
    flagged: "Flagged",
    draft: "Draft",
    label: "Status: {status}",
  },
  review: {
    overline: "Supervisor",
    title: "Review queue · {count}",
    filterLabel: "Filter by reason",
    filters: {
      all: "All reasons",
      low_confidence: "Low AI confidence",
      gps: "GPS",
      duplicate: "Duplicates",
    },
    reasons: {
      low_confidence: "Low AI confidence ({confidence})",
      gps_unverified: "GPS unverified (±{accuracy} m draft)",
      heavy_edits: "Heavy edits ({edited} of {total} attributes)",
      duplicate: "Possible duplicate ({distance} m)",
    },
    meta: "{enumerator} · {when}",
    today: "today {time}",
    yesterday: "yesterday",
    openRecord: "{title}, {meta}. Open record",
    approve: "Approve",
    reject: "Reject",
    approveLabel: "Approve {title}",
    rejectLabel: "Reject {title}",
    rejectReasonLabel: "Why reject {title}?",
    rejectReasons: {
      wrong_class: "Wrong asset class",
      poor_photo: "Poor photo",
      bad_location: "Bad location",
      duplicate: "Duplicate",
      other: "Other",
    },
    cancel: "Cancel",
    confirmReject: "Confirm reject",
    empty: {
      all: "The queue is clear. Download a batch to review more.",
      filtered: "No records waiting for this reason.",
    },
    scopes: {
      label: "Show review",
      team: "Team queue",
      mine: "My records",
    },
    batch: {
      label: "Review batch",
      none: "Download records to review. You can decide them offline.",
      summary: "Batch of {size} · downloaded {when}",
      unsent: "{count} decisions waiting to upload",
      unsentOne: "1 decision waiting to upload",
      download: "Download batch",
      downloadNext: "Download next batch",
      downloading: "Downloading…",
      offline:
        "Connect to download a batch. Decisions made offline upload later.",
      nothingNew: "Nothing new waiting on the server.",
      added: "{count} records added to your queue.",
      failed: "Couldn’t download the batch. Try again.",
    },
    mine: {
      overline: "Review",
      title: "My records in review · {count}",
      intro:
        "Records routed to a supervisor for low AI confidence, GPS or a possible duplicate.",
      empty: "None of your records are waiting for a supervisor.",
      states: {
        waiting: "Waiting",
        approved: "Approved",
        rejected: "Rejected",
      },
      waitingNote: "Waiting for a supervisor",
      rejectedBecause: "Rejected: {reason}. Edit the record to fix it.",
      rowLabel: "{title}, {meta}, {state}. Open record",
    },
  },
  settings: {
    title: "Settings",
    account: {
      fallbackName: "Signed-in user",
      roles: {
        admin: "Administrator",
        supervisor: "Supervisor",
        enumerator: "Field enumerator",
      },
      roleAndOrg: "{role} · {org}",
      sso: "Casdoor SSO",
      password: "Username and password",
      offlineSession: "Session renews offline for {days} days",
      switchProject: "Switch project · {project}",
      noProject: "Choose a project",
    },
    capture: {
      title: "Capture",
      accuracyGate: "GPS accuracy gate",
      accuracyGateHint: "Set by your administrator",
      accuracyGateValue: "< {value} m",
      gnss: "External GNSS receiver",
      gnssHint: "Bluetooth RTK for sub-metre work",
      gnssNone: "None",
      photosPerAsset: "Photos per asset",
      photosPerAssetValue: "Up to {count}",
      photosPerAssetOne: "1 photo",
      photoQuality: "Photo quality",
      photoQualities: { high: "High · 12 MP", standard: "Standard · 5 MP" },
      framingGuides: "Framing guides in camera",
      voiceComments: "Voice-to-text comments",
    },
    sync: {
      title: "Sync",
      wifiOnly: "Upload photos on Wi-Fi only",
      wifiOnlyHint: "Record data still syncs on mobile data",
      background: "Sync in the background",
      lastSynced: "Last synced",
      never: "Never",
      today: "Today {time}",
      yesterday: "Yesterday {time}",
      waiting: "{count} records waiting",
      waitingOne: "1 record waiting",
      allSynced: "Everything is synced",
      syncNow: "Sync now",
      syncing: "Syncing…",
    },
    model: {
      title: "AI model",
      onDevice: "On-device model",
      updateAvailable: "Update available",
      updateHint: "{version} · {size} · {note}",
      download: "Download",
      cloudEnrichment: "Cloud enrichment after sync",
      cloudEnrichmentHint: "Adds age and size estimates",
      showConfidence: "Show AI confidence on attributes",
    },
    privacy: {
      title: "Privacy & security",
      blur: "Blur faces and number plates",
      blurHint: "Required by project policy",
      on: "On",
      off: "Off",
      biometric: "Unlock with fingerprint or face",
      devices: "Signed-in devices",
    },
    general: {
      title: "General",
      language: "Language",
      languages: { en: "English" },
      units: "Units",
      unitOptions: { metric: "Metric", imperial: "Imperial" },
      offlineTiles: "Offline map tiles",
      noTiles: "None",
    },
    about: {
      title: "About",
      appVersion: "App version",
      server: "Server",
      terms: "Terms and privacy policy",
    },
    appearance: {
      title: "Appearance",
      theme: "Theme",
      themes: {
        system: "System",
        light: "Light",
        dark: "Dark",
        outdoor: "Outdoor",
      },
      outdoorHint:
        "Outdoor mode uses heavier text and higher contrast for direct sunlight.",
    },
    storage: {
      title: "Storage on this device",
      appData: "App data",
      megabytes: "{value} MB",
      gigabytes: "{value} GB",
      photos: "Photos {size}",
      map: "Map {size}",
      model: "Model {size}",
      usageLabel: "Photos {photos}, map {map}, model {model}",
      clearSynced: "Clear photos already synced",
      clearTitle: "Clear synced photos?",
      clearMessage:
        "Frees {size}. The photos stay on the server and in each record.",
      clearConfirm: "Clear",
      cancel: "Cancel",
    },
    signOut: {
      button: "Sign out",
      unsynced:
        "{count} records haven’t synced. Sync before signing out, or they stay on this device until you sign back in.",
      unsyncedOne:
        "1 record hasn’t synced. Sync before signing out, or it stays on this device until you sign back in.",
      confirmTitle: "Sign out",
      confirmMessage: "Are you sure you want to sign out?",
      cancel: "Cancel",
    },
    lockedLabel: "Set by administrator",
    unavailable: "Not available yet",
    choose: "Choose {setting}",
  },
  map: {
    searchLabel: "Search assets or IDs",
    searchPlaceholder: "Search assets or IDs",
    clearSearch: "Clear search",
    filterLabel: "Filter by category",
    filters: {
      all: "All",
      energy: "Energy",
      water: "Water",
      telecom: "Telecom",
      roads: "Roads",
    },
    offline: "Offline map · cached tiles",
    noMatches: "No assets match. Try another search or category.",
    mapLabel: "Map with {count} captured assets",
    layers: "Map layers",
    locate: "Center on my location",
    unavailableTitle: "Map",
    unavailableMessage:
      "The asset map runs in the mobile app. Open it on your Android or iOS device.",
    layersSheet: {
      title: "Map layers",
      basemap: "Basemap",
      basemaps: { streets: "Streets", light: "Light", satellite: "Satellite" },
      cluster: "Group nearby pins",
      clusterHint: "Show numbered clusters when zoomed out.",
      done: "Done",
    },
    asset: {
      label: "Selected asset",
      meta: "{id} · last seen {when}",
      away: "{distance} away",
      today: "today {time}",
      metres: "{value} m",
      kilometres: "{value} km",
      recapture: "Re-capture",
      viewRecord: "View record",
      close: "Close asset",
      showProfile: "Show asset profile",
      hideProfile: "Hide asset profile",
      inclined: "Inclined {value}°",
      vegetation: "Vegetation: {value}",
    },
    profile: {
      attributes: "Attributes",
      location: "Location",
      record: "Record",
      coordinates: "Coordinates",
      accuracy: "Accuracy",
      accuracyValue: "±{value} m",
      elevation: "Elevation",
      elevationValue: "{value} m",
      functional: "Functional",
      firstRecorded: "First recorded",
      lastSeen: "Last seen",
      capturedBy: "Captured by",
      photos: "Photos",
      sync: "Sync",
      flagged: "Flagged for supervisor review",
      comment: "Comment",
      notReported: "—",
    },
  },
} as const;
