/**
 * User-facing copy. Keep labels here (not inline) so they can move to an i18n
 * catalogue without touching components.
 */
export const strings = {
  auth: {
    title: "Intelligent\nInfrastructure\nPlatform",
    subtitle: "Map, inspect and report public infrastructure from the field.",
    logoLabel: "Intelligent Infrastructure Platform logo",
    continueWithSso: "Continue with SSO",
    continueWithGoogle: "Continue with Google",
    orWithUsername: "or with username",
    usernameLabel: "Username or email",
    usernamePlaceholder: "name@organisation.org",
    passwordLabel: "Password",
    forgotPassword: "Forgot password?",
    showPassword: "Show password",
    hidePassword: "Hide password",
    keepSignedIn: "Keep me signed in on this device",
    signIn: "Sign in",
    newToPlatform: "New to the platform?",
    createAccount: "Create an account",
    changeServer: "Change server",
    serverOnline: "Server reachable",
    serverOffline: "No connection",
    comingSoonTitle: "Coming soon",
    comingSoonMessage: "This option isn't available yet.",
    errors: {
      invalidCredentials: "That username or password is incorrect.",
      ssoOffline: "SSO needs a connection. Sign in with your username instead.",
      ssoFailed: "SSO sign-in didn't complete. Please try again.",
      serverUnreachable: "Could not reach the server. Please try again.",
      accountPending:
        "Your account is waiting for approval. You can sign in once an administrator approves it.",
    },
  },
  register: {
    back: "Back to sign in",
    title: "Create an account",
    subtitle:
      "Join the Intelligent Infrastructure Platform to capture and report assets in your area.",
    nameLabel: "Full name",
    emailLabel: "Work email",
    emailPlaceholder: "name@organisation.org",
    phoneLabel: "Phone number",
    phonePlaceholder: "+256",
    optional: "(optional)",
    passwordLabel: "Password",
    confirmPasswordLabel: "Confirm password",
    passwordHint: "At least 10 characters with a number",
    passwordRule: "at least 10 characters with a number",
    strength: {
      weak: "Weak",
      fair: "Fair",
      strong: "Strong",
      veryStrong: "Very strong",
    },
    termsPrefix: "I agree to the ",
    termsOfUse: "terms of use",
    termsJoin: " and ",
    privacyPolicy: "privacy policy",
    termsSuffix: ", including how photos and locations are stored.",
    verificationNote:
      "We’ll email a verification link. An administrator then approves your role and assigns your project area.",
    submit: "Create account",
    haveAccount: "Already have an account?",
    signIn: "Sign in",
    successTitle: "Check your email",
    successSentTo: "We sent a verification link to",
    successNext:
      "Open it to confirm your address. An administrator then approves your role and assigns your project area.",
    errors: {
      nameRequired: "Enter your full name.",
      emailRequired: "Enter your work email.",
      emailInvalid: "Enter a valid email, like name@organisation.org.",
      phoneInvalid: "Include the country code, like +256 700 123 456.",
      passwordRequired: "Choose a password.",
      passwordWeak: "Use at least 10 characters with a number.",
      confirmMismatch: "The passwords don’t match.",
      termsRequired: "Accept the terms of use and privacy policy to continue.",
    },
    submitErrors: {
      offline:
        "Creating an account needs a connection. Try again when you’re online.",
      email_taken:
        "An account with this email already exists. Sign in instead.",
      invalid: "Some details weren’t accepted. Check the form and try again.",
      server_unreachable: "Could not reach the server. Please try again.",
    },
  },
  categories: {
    energy: {
      label: "Energy & Power",
      description: "Poles, substations, solar, street lights",
    },
    water: {
      label: "Water & Sanitation",
      description: "Boreholes, taps, wells, tanks, toilets",
    },
    telecom: {
      label: "Telecom",
      description: "Masts, telecom poles, cabinets",
    },
    roads: {
      label: "Roads & Drainage",
      description: "Culverts, bridges, potholes, drains",
    },
  },
  tabs: {
    capture: "Capture",
    map: "Map",
    records: "Records",
    review: "Review",
    profile: "Profile",
  },
  syncStatus: {
    pending: "waiting to sync",
    uploading: "uploading",
    synced: "synced",
    failed: "sync failed",
  },
  home: {
    overline: "IIP · {org}",
    overlineNoOrg: "IIP",
    title: "Field capture",
    pending: "{count} pending",
    pendingLabel: "{count} records waiting to sync. Open records",
    profileLabel: "Profile and settings",
    todayLabel: "Today",
    capturedToday: "Captured today",
    synced: "Synced",
    flagged: "Flagged",
    gnss: "GNSS",
    gnssNoFix: "No fix",
    heading: "What are you capturing?",
    aiPick: "Not sure? Let AI pick the category",
    lastCaptured: "Last captured",
    nothingYet: "Nothing captured yet. Pick a category to start.",
  },
  capture: {
    close: "Close camera",
    flashOn: "Flash on",
    flashOff: "Flash off",
    autoCategory: "AI picks category",
    gpsRegion: "GPS accuracy",
    accuracyUnit: "m",
    status: {
      acquiring: "Acquiring accurate fix…",
      imprecise: "Acquiring accurate fix…",
      confirming: "Confirming fix…",
      ready: "Location locked",
      unknown: "GPS precision unknown",
      denied: "Location permission needed",
      error: "Location unavailable",
    },
    satellites: "{count} sats",
    stableFixes: "{count} of 3 stable fixes",
    meterStart: "8 m",
    meterTarget: "Target 4 m",
    meterEnd: "0 m",
    hint: {
      waiting: "Step into open sky, away from walls and trees",
      energy: "Fit the whole pole, top to base",
      water: "Fit the whole structure in the frame",
      telecom: "Fit the whole mast or cabinet in the frame",
      roads: "Frame the full width of the culvert, drain or damage",
      auto: "Fit the whole asset in the frame",
    },
    shutter: "Take photo",
    shutterLocked: "Take photo — locked until GPS accuracy is under 4 metres",
    shutterNoteReady: "Location is stamped when you tap",
    shutterNoteLocked: "Capture unlocks below 4 m",
    saveDraft: "Can’t get below 4 m? Save as draft for review",
    photosTaken: "Photos taken: {count} of 3",
    photoSlot: "Photo {index}. Tap to retake",
    photoOf: "Photo {index} of 3",
    sharp: "sharp",
    blurry: "blurry",
    exposureOk: "exposure OK",
    exposureBad: "check exposure",
    continue: "Continue",
    detected: "{count} detected",
    detectionsNone: "Nothing detected yet",
    suggested: "suggested",
    confidenceHigh: "AI · high",
    confidenceMedium: "AI · medium",
    model: {
      loading: "Loading AI model… {percent}%",
      unavailable:
        "AI detection unavailable. You can still capture; the record is checked after sync.",
    },
    permissions: {
      title: "Camera & location access",
      message:
        "Capture needs the camera, and your location to pin the asset to under 4 m.",
      grant: "Allow access",
    },
    noCamera: "No back camera was found on this device.",
    tag: {
      title: "Tag this asset",
      back: "Back to review",
      step: "Step 3 of 3",
      kept: "{count} detections kept",
      keptOne: "1 detection kept",
      keptNone: "No detections kept",
      category: "Category",
      status: "Status",
      statusHint: "Select all that apply. AI suggestions are pre-selected.",
      pickCategoryFirst: "Pick a category to see its statuses.",
      functional: "Functional?",
      functionalHint: "The AI can’t judge this from a photo.",
      functionalOptions: { yes: "Yes", no: "No", unknown: "Unknown" },
      comment: "Comment",
      commentPlaceholder: "Add notes about the asset…",
      dictate: "Dictate comment",
      stopDictation: "Stop dictation",
      listening: "Listening…",
      dictationFailed: "Voice input didn’t work. Please type the comment.",
      duplicateTitle: "Possible duplicate.",
      duplicateMessage:
        "A {label} ({id}) was recorded {distance} m away on {date}.",
      duplicateAsset: "asset",
      updateExisting: "Update the existing asset",
      newAsset: "This is a new asset",
      latitude: "Latitude",
      longitude: "Longitude",
      elevation: "Elevation (ellipsoid)",
      accuracy: "Accuracy",
      elevationValue: "{value} m",
      accuracyValue: "±{accuracy} m",
      satellites: "{count} sats",
      notReported: "—",
      draftLocation: "Location not verified: saved for supervisor review.",
      saveDraft: "Save draft",
      save: "Save record",
      needCategory: "Pick a category to save.",
      needStatus: "Pick at least one status to save the record.",
      needDuplicate: "Say whether this is the existing asset or a new one.",
      editTitle: "Edit record",
      editBack: "Back to record",
      saveChanges: "Save changes",
    },
    statuses: {
      good: "Good condition",
      inclined: "Inclined",
      vegetation: "Covered by vegetation",
      cracked: "Cracked / damaged",
      rust: "Rust / rot",
      sagging_lines: "Sagging lines",
      under_construction: "Under construction",
      leaking: "Leaking",
      blocked: "Blocked",
      eroded: "Eroded",
      potholes: "Potholes",
      vandalised: "Vandalised",
    },
    errors: {
      captureTitle: "Capture failed",
      captureMessage: "The photo could not be taken.",
      saveTitle: "Save failed",
      saveMessage: "The capture could not be saved. Please try again.",
    },
    review: {
      title: "Review detections",
      back: "Back to camera",
      step: "Step 2 of 3",
      subtitle: "{category} · {count} found · model {model}",
      autoCategory: "AI category",
      photoSummary: "Photo with {count} detections",
      boxLabel: "{index} {label} · {confidence}",
      legendAccepted: "Pre-accepted ≥ 0.70",
      legendSuggested: "Suggested 0.40–0.70",
      confidence: "Confidence {confidence}",
      suggested: "Suggested · confidence {confidence}",
      rejected: "Not an asset · confidence {confidence}",
      accepted: "Accepted",
      accept: "Accept",
      reject: "Not an asset",
      undo: "Undo",
      expand: "Show {label} attributes",
      collapse: "Hide {label} attributes",
      pleaseCheck: "Please check",
      source: {
        high: "AI · high",
        medium: "AI · medium",
        low: "AI · low",
        ai: "AI",
        gis: "GIS",
        user: "User",
      },
      pending: "Estimated after sync",
      gisPending: "Calculated after sync",
      edit: "Change {attribute}",
      editTitle: "{attribute}",
      noneFound:
        "No assets were detected. Continue to tag the photo, or add another.",
      addPhoto: "Add photo",
      continue: "Continue to tagging",
    },
  },
  attributes: {
    material: {
      label: "Material",
      values: { concrete: "Concrete", metal: "Metallic", wood: "Wood" },
    },
    inclination: { label: "Inclination", format: "{value}° from vertical" },
    estimatedAge: {
      label: "Estimated age",
      values: {
        "0-5": "0–5 years",
        "5-10": "5–10 years",
        "10-20": "10–20 years",
        "20+": "Over 20 years",
      },
    },
    estimatedSize: {
      label: "Estimated size",
      values: { small: "Small", medium: "Medium", large: "Large" },
    },
    vegetationCover: {
      label: "Vegetation cover",
      values: { none: "None", partial: "Partial", heavy: "Heavy" },
    },
    countInFrame: { label: "Count in frame", format: "{value}" },
    distanceFromRoad: { label: "Distance from main road", format: "{value} m" },
  },
  camera: {
    unavailableTitle: "Camera capture",
    unavailableMessage:
      "Camera and AI detection run in the mobile app. Open it on your Android or iOS device to capture assets.",
  },
  records: {
    title: "Records",
    openSearch: "Search records",
    closeSearch: "Close search",
    searchLabel: "Search by name, ID or category",
    searchPlaceholder: "Search by name, ID or category",
    clearSearch: "Clear search",
    filterLabel: "Filter records",
    filters: {
      all: "All · {count}",
      pending: "Pending · {count}",
      flagged: "Flagged · {count}",
    },
    today: "Today",
    yesterday: "Yesterday",
    detections: "{count} detections",
    functional: { yes: "functional", no: "not working" },
    rowLabel: "{title}, {meta}, {status}",
    banner: {
      label: "Sync status",
      waitingOne: "1 record waiting to upload",
      waiting: "{count} records waiting to upload",
      uploading: "Uploading…",
      failed: "{count} failed to upload · tap Sync now to retry",
      offline: "No network · photos upload on Wi-Fi",
      online: "Photos upload on Wi-Fi",
      syncNow: "Sync now",
    },
    empty: {
      all: "No records yet. Captures you save appear here.",
      pending: "Nothing waiting to upload.",
      flagged: "No flagged records.",
      search: "No records match your search.",
    },
    detail: {
      back: "Back to records",
      photos: "Photos",
      photoCount: "{index} of {count} photos",
      photoOne: "1 photo",
      photoLabel: "Photo {index} of {count}",
      noPhoto: "No photo on this device",
      captured: "{id} · captured {when}",
      capturedNoId: "Captured {when}",
      attributes: "Attributes",
      source: "Source",
      status: "Status",
      noStatus: "Not recorded",
      comment: "Comment",
      location: "Location",
      history: "Condition history",
      thisCapture: "{date} · this capture",
      showOnMap: "Show on map",
      edit: "Edit record",
      notFound: "This record isn’t on this device.",
      backToRecords: "Back to records",
      sync: {
        pending: "Waiting to sync",
        uploading: "Uploading",
        synced: "Synced",
        failed: "Sync failed",
      },
      flagged: "Flagged for review",
      condition: {
        inclined: "inclined {value}°",
        vegetation: {
          none: "no vegetation",
          partial: "partial vegetation",
          heavy: "heavy vegetation",
        },
        none: "No condition recorded",
      },
    },
  },
  recordStatus: {
    synced: "Synced",
    pending: "Pending",
    uploading: "Uploading",
    failed: "Sync failed",
    flagged: "Flagged",
    draft: "Draft",
    label: "Status: {status}",
  },
  review: {
    title: "Review",
    comingSoon: "The supervisor review queue is coming soon.",
  },
  map: {
    searchLabel: "Search assets or IDs",
    searchPlaceholder: "Search assets or IDs",
    clearSearch: "Clear search",
    filterLabel: "Filter by category",
    filters: {
      all: "All",
      energy: "Energy",
      water: "Water",
      telecom: "Telecom",
      roads: "Roads",
    },
    offline: "Offline map · cached tiles",
    noMatches: "No assets match. Try another search or category.",
    mapLabel: "Map with {count} captured assets",
    layers: "Map layers",
    locate: "Center on my location",
    unavailableTitle: "Map",
    unavailableMessage:
      "The asset map runs in the mobile app. Open it on your Android or iOS device.",
    layersSheet: {
      title: "Map layers",
      basemap: "Basemap",
      basemaps: { streets: "Streets", light: "Light", satellite: "Satellite" },
      cluster: "Group nearby pins",
      clusterHint: "Show numbered clusters when zoomed out.",
      done: "Done",
    },
    asset: {
      label: "Selected asset",
      meta: "{id} · last seen {when}",
      away: "{distance} away",
      today: "today {time}",
      metres: "{value} m",
      kilometres: "{value} km",
      recapture: "Re-capture",
      viewRecord: "View record",
      close: "Close asset",
      showProfile: "Show asset profile",
      hideProfile: "Hide asset profile",
      inclined: "Inclined {value}°",
      vegetation: "Vegetation: {value}",
    },
    profile: {
      attributes: "Attributes",
      location: "Location",
      record: "Record",
      coordinates: "Coordinates",
      accuracy: "Accuracy",
      accuracyValue: "±{value} m",
      elevation: "Elevation",
      elevationValue: "{value} m",
      functional: "Functional",
      firstRecorded: "First recorded",
      lastSeen: "Last seen",
      capturedBy: "Captured by",
      photos: "Photos",
      sync: "Sync",
      flagged: "Flagged for supervisor review",
      comment: "Comment",
      notReported: "—",
    },
  },
} as const;
