/**
 * User-facing copy. Keep labels here (not inline) so they can move to an i18n
 * catalogue without touching components.
 */
export const strings = {
  auth: {
    title: "Intelligent\nInfrastructure\nPlatform",
    subtitle: "Map, inspect and report public infrastructure from the field.",
    logoLabel: "Intelligent Infrastructure Platform logo",
    continueWithSso: "Continue with SSO",
    continueWithGoogle: "Continue with Google",
    orWithUsername: "or with username",
    usernameLabel: "Username or email",
    usernamePlaceholder: "name@organisation.org",
    passwordLabel: "Password",
    forgotPassword: "Forgot password?",
    showPassword: "Show password",
    hidePassword: "Hide password",
    keepSignedIn: "Keep me signed in on this device",
    signIn: "Sign in",
    newToPlatform: "New to the platform?",
    createAccount: "Create an account",
    changeServer: "Change server",
    serverOnline: "Server reachable",
    serverOffline: "No connection",
    comingSoonTitle: "Coming soon",
    comingSoonMessage: "This option isn't available yet.",
    errors: {
      invalidCredentials: "That username or password is incorrect.",
      ssoOffline: "SSO needs a connection. Sign in with your username instead.",
      ssoFailed: "SSO sign-in didn't complete. Please try again.",
      serverUnreachable: "Could not reach the server. Please try again.",
      accountPending:
        "Your account is waiting for approval. You can sign in once an administrator approves it.",
    },
  },
  register: {
    back: "Back to sign in",
    title: "Create an account",
    subtitle:
      "Join the Intelligent Infrastructure Platform to capture and report assets in your area.",
    nameLabel: "Full name",
    emailLabel: "Work email",
    emailPlaceholder: "name@organisation.org",
    phoneLabel: "Phone number",
    phonePlaceholder: "+256",
    optional: "(optional)",
    passwordLabel: "Password",
    confirmPasswordLabel: "Confirm password",
    passwordHint: "At least 10 characters with a number",
    passwordRule: "at least 10 characters with a number",
    strength: {
      weak: "Weak",
      fair: "Fair",
      strong: "Strong",
      veryStrong: "Very strong",
    },
    termsPrefix: "I agree to the ",
    termsOfUse: "terms of use",
    termsJoin: " and ",
    privacyPolicy: "privacy policy",
    termsSuffix: ", including how photos and locations are stored.",
    verificationNote:
      "We’ll email a verification link. An administrator then approves your role and assigns your project area.",
    submit: "Create account",
    haveAccount: "Already have an account?",
    signIn: "Sign in",
    successTitle: "Check your email",
    successSentTo: "We sent a verification link to",
    successNext:
      "Open it to confirm your address. An administrator then approves your role and assigns your project area.",
    errors: {
      nameRequired: "Enter your full name.",
      emailRequired: "Enter your work email.",
      emailInvalid: "Enter a valid email, like name@organisation.org.",
      phoneInvalid: "Include the country code, like +256 700 123 456.",
      passwordRequired: "Choose a password.",
      passwordWeak: "Use at least 10 characters with a number.",
      confirmMismatch: "The passwords don’t match.",
      termsRequired: "Accept the terms of use and privacy policy to continue.",
    },
    submitErrors: {
      offline:
        "Creating an account needs a connection. Try again when you’re online.",
      email_taken:
        "An account with this email already exists. Sign in instead.",
      invalid: "Some details weren’t accepted. Check the form and try again.",
      server_unreachable: "Could not reach the server. Please try again.",
    },
  },
  categories: {
    energy: {
      label: "Energy & Power",
      description: "Poles, substations, solar, street lights",
    },
    water: {
      label: "Water & Sanitation",
      description: "Boreholes, taps, wells, tanks, toilets",
    },
    telecom: {
      label: "Telecom",
      description: "Masts, telecom poles, cabinets",
    },
    roads: {
      label: "Roads & Drainage",
      description: "Culverts, bridges, potholes, drains",
    },
  },
  tabs: {
    capture: "Capture",
    map: "Map",
    records: "Records",
    review: "Review",
    profile: "Profile",
  },
  syncStatus: {
    pending: "waiting to sync",
    uploading: "uploading",
    synced: "synced",
    failed: "sync failed",
  },
  home: {
    overline: "IIP · {org}",
    overlineNoOrg: "IIP",
    title: "Field capture",
    pending: "{count} pending",
    pendingLabel: "{count} records waiting to sync. Open records",
    profileLabel: "Profile and settings",
    todayLabel: "Today",
    capturedToday: "Captured today",
    synced: "Synced",
    flagged: "Flagged",
    gnss: "GNSS",
    gnssNoFix: "No fix",
    heading: "What are you capturing?",
    aiPick: "Not sure? Let AI pick the category",
    lastCaptured: "Last captured",
    nothingYet: "Nothing captured yet. Pick a category to start.",
  },
  capture: {
    close: "Close camera",
    flashOn: "Flash on",
    flashOff: "Flash off",
    autoCategory: "AI picks category",
    gpsRegion: "GPS accuracy",
    accuracyUnit: "m",
    status: {
      acquiring: "Acquiring accurate fix…",
      imprecise: "Acquiring accurate fix…",
      confirming: "Confirming fix…",
      ready: "Location locked",
      unknown: "GPS precision unknown",
      denied: "Location permission needed",
      error: "Location unavailable",
    },
    satellites: "{count} sats",
    stableFixes: "{count} of 3 stable fixes",
    meterStart: "8 m",
    meterTarget: "Target 4 m",
    meterEnd: "0 m",
    hint: {
      waiting: "Step into open sky, away from walls and trees",
      energy: "Fit the whole pole, top to base",
      water: "Fit the whole structure in the frame",
      telecom: "Fit the whole mast or cabinet in the frame",
      roads: "Frame the full width of the culvert, drain or damage",
      auto: "Fit the whole asset in the frame",
    },
    shutter: "Take photo",
    shutterLocked: "Take photo — locked until GPS accuracy is under 4 metres",
    shutterNoteReady: "Location is stamped when you tap",
    shutterNoteLocked: "Capture unlocks below 4 m",
    saveDraft: "Can’t get below 4 m? Save as draft for review",
    photosTaken: "Photos taken: {count} of 3",
    photoSlot: "Photo {index}. Tap to retake",
    photoOf: "Photo {index} of 3",
    sharp: "sharp",
    blurry: "blurry",
    exposureOk: "exposure OK",
    exposureBad: "check exposure",
    continue: "Continue",
    detected: "{count} detected",
    detectionsNone: "Nothing detected yet",
    suggested: "suggested",
    confidenceHigh: "AI · high",
    confidenceMedium: "AI · medium",
    model: {
      loading: "Loading AI model… {percent}%",
      unavailable:
        "AI detection unavailable. You can still capture; the record is checked after sync.",
    },
    permissions: {
      title: "Camera & location access",
      message:
        "Capture needs the camera, and your location to pin the asset to under 4 m.",
      grant: "Allow access",
    },
    noCamera: "No back camera was found on this device.",
    form: {
      detections: "{count} assets detected",
      detectionsOne: "1 asset detected",
      detectionsNone: "No assets detected",
      accuracy: "GPS ±{accuracy} m",
      draft: "Draft · location not verified",
      category: "Category",
      status: "Status",
      statusPlaceholder: "Select a status…",
      comment: "Comment",
      commentPlaceholder: "Add additional notes…",
      retake: "Back to camera",
      save: "Save",
      pickStatus: "Pick a status to enable saving.",
      pickCategory: "Pick a category to enable saving.",
    },
    tags: {
      good: "Good",
      fair: "Fair",
      poor: "Poor",
      damaged: "Damaged",
      not_functional: "Not functional",
      other: "Other",
    },
    errors: {
      captureTitle: "Capture failed",
      captureMessage: "The photo could not be taken.",
      saveTitle: "Save failed",
      saveMessage: "The capture could not be saved. Please try again.",
    },
  },
  camera: {
    unavailableTitle: "Camera capture",
    unavailableMessage:
      "Camera and AI detection run in the mobile app. Open it on your Android or iOS device to capture assets.",
  },
  records: {
    title: "Records",
    pendingSummary: "{count} records waiting to sync.",
    comingSoon: "Browsing and filtering records is coming soon.",
  },
  review: {
    title: "Review",
    comingSoon: "The supervisor review queue is coming soon.",
  },
} as const;
